# This is a basic workflow to help you get started with Actions

name: Generate Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-18.04
    container:
      image: docker.pkg.github.com/nvidia/trtorch/docgen:latest
      credentials:
        username: $GITHUB_ACTOR
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: Build Python Package
        run: |
          cp docker/WORKSPACE.docs WORKSPACE
          cd py
          python3 setup.py install
      - name: Generate New Docs
        run: |
          cd docsrc
          make html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
        # Required
          commit_message: "docs: [Automated] Regenerating documenation from $GITHUB_SHA"
          commit_options: "--no-verify --signoff"
          file_pattern: docs/
          commit_user_name: TRTorch Github Bot
          commit_user_email: trtorch.github.bot@nvidia.com
          commit_author: TRTorch Github Bot <trtorch.github.bot@nvidia.com>
